### ISSUE TITLE
Core test buffer_copy, openCL return CL_INVALID_CONTEXT

### ISSUE THREAD

**Issue by Kerosene2000** [Kerosene2000/ocl-core#1]
Hi @c0gent,

I have a little problem on moving `ocl` tests to `ocl-core`.
https://github.com/Kerosene2000/ocl-core/blob/ocl-core_buffer_copy/src/tests/buffer_copy.rs

When I try to execute the buffer_copy test, it returns `CL_INVALID_CONTEXT` on `clReleaseContext` (on drop I suppose), and I don't know why...

I just create a context with the first platform/device nothing else.

**Comment by Kerosene2000** [comment]
Same error on https://github.com/Kerosene2000/ocl-core/blob/ocl-core_buffer_copy/src/tests/buffer_fill.rs.
I think I really forgot something, but what ?

**Comment by c0gent** [comment]
Yes this is the `.ok()` vs `.unwrap()` issue. Ok so what I'm going to do is add some logic which will ignore `CL_INVALID_CONTEXT` when `drop()` is called for `ocl_core::Context`. That sound ok to you?

**Comment by Kerosene2000** [comment]
Seem's good but how can we fix this ? For really I mean.

**Comment by Kerosene2000** [comment]
\+ It seems `cargo test`  compile with `--release` option. (If I have this error => `unwrap()`).

**Comment by c0gent** [comment]
I'm not sure why sometimes you get `CL_INVALID_CONTEXT` this only happens on certain platforms and I think it's just a bug in the driver. I think the only fix is to ignore it but I'm open to suggestions.

**Comment by Kerosene2000** [comment]
I propose to let an issue open, and ignore the error for the moment, like you say.

**Comment by c0gent** [comment]
Ok. I'll push that update shortly.

**Comment by c0gent** [comment]
Ok try the latest updates: https://github.com/cogciprocate/ocl-core/commit/999edddec9dc913cf49dce634512ffe54fa87bfd.

**Comment by Kerosene2000** [comment]
hmmmm `CL_INVALID_DEVICE` on `clCreateContext` now... but it can be me...

**Comment by c0gent** [comment]
So strange. It's probably your driver being weird. Let's try to find a workaround or a fix. I can't reproduce this on any of my machines.

**Comment by c0gent** [comment]
Ok wait I just noticed you've changed something in that test.

**Comment by c0gent** [comment]
So yeah it is you :)

https://github.com/Kerosene2000/ocl-core/commit/635b2c7f3bd74133e7d4ff23642441a9966474cc#diff-f7ee5346a0d33b172f38745dd3b3ebc0L19

**Comment by Kerosene2000** [comment]
Where is the problem ? the red version doesn't compile

**Comment by c0gent** [comment]
Doesn't the original configuration work?

```
    let platform_id = core::default_platform().unwrap();
    let device_ids = core::get_device_ids(&platform_id, None, None).unwrap();
    let device_id = device_ids[0];
    let context_properties = ContextProperties::new().platform(platform_id);
    let context = core::create_context(&Some(context_properties),
        &[device_id], None, None).unwrap();
```

**Comment by c0gent** [comment]
Looks like your version has you getting the 'first' platform rather than the default. I'm guessing you have another platform on your system which is somehow not working.

**Comment by Kerosene2000** [comment]
Ho yup, you are right, it works !
Sorry ! but what is this platform ? 😕

**Comment by c0gent** [comment]
Don't know, does it show up when you do `cargo run --example info_core`?

**Comment by c0gent** [comment]
Or `clinfo`?

**Comment by c0gent** [comment]
Actually the `ocl` example: `info` is better to look.

**Comment by Kerosene2000** [comment]
```
Platform:
    Profile: FULL_PROFILE
    Version: OpenCL 1.2 (Jul 24 2016 23:29:53)
    Name: Apple
    Vendor: Apple
    Extensions: cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event
```

```
Platform:
    Profile: FULL_PROFILE
    Version: OpenCL 1.2 (Jul 24 2016 23:29:53)
    Name: Apple
    Vendor: Apple
    Extensions: cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event
```

I don't know...

**Comment by c0gent** [comment]
Try the `ocl`: `info.rs`.

**Comment by Kerosene2000** [comment]
hummm...
<img width="1440" alt="capture d ecran 2016-08-08 a 20 38 48" src="https://cloud.githubusercontent.com/assets/3610253/17491500/24c56db0-5da8-11e6-915f-7eb922b73108.png">

**Comment by c0gent** [comment]
No, ok I'm wrong there's only one. I really don't know then... there must have been something else wrong with the code.

**Comment by c0gent** [comment]
Try just swapping the platform line with this: 
```
let platform_id = ::get_platform_ids().unwrap().first().unwrap().clone();
```

and see what happens.

**Comment by Kerosene2000** [comment]
it works... but wtf ? :/

**Comment by c0gent** [comment]
Something else is wrong somewhere.

**Comment by Kerosene2000** [comment]
I will keep `platform_default` for the moment and for the tests...

**Comment by c0gent** [comment]
Yes It's best like that anyway because it will take `OCL_DEFAULT_PLATFORM_IDX` into account.

**Comment by c0gent** [comment]
Most likely your driver is glitchy because I don't see any problems with your other code.

**Comment by c0gent** [comment]
Blame it on Apple.
